### ISSUE TITLE
Query: sending metrics to prometheus cloud

### ISSUE THREAD

**Issue by akshayr-hub** [monodot/spring-boot-with-metrics#6]
Hello 

Thank you for this example

How can we send metrics directly to prometheus cloud?

**Comment by monodot** [comment]
Hey, you're welcome.

I don't know Prometheus Cloud, so I can't really answer your question. Which company runs the service?

Generally speaking, your cloud provider should provide instructions on how to do this. This example app **exposes** metrics. In the tutorial, we configure a local Prometheus instance to **scrape** the metrics.

But when using a cloud service, you would generally run a local Agent, which **scrapes** the metrics from all your applications, and then **pushes** them to a remote (cloud) Prometheus instance. If you're using a cloud-hosted Prometheus service, then they should provide some Agent, or docs on how to do this.

For example, you can use [Grafana Agent](https://grafana.com/docs/agent/latest/) to find targets (== your applications), scrape the metrics and push them to Grafana Cloud Metrics (using Prometheus's remote-write).

Hope this helps.
